# Generated by Django 5.1.5 on 2025-08-03 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('payment_type', models.CharField(choices=[('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, upload_to='payment_methods/', verbose_name='Logo')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='Clé API')),
                ('api_secret', models.CharField(blank=True, max_length=200, verbose_name='Secret API')),
                ('merchant_id', models.CharField(blank=True, max_length=100, verbose_name='ID Marchand')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Montant maximum')),
                ('fees_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Frais (%)')),
                ('fees_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais fixes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID Paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('api_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse API')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='Méthode de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('billing_name', models.CharField(max_length=200, verbose_name='Nom de facturation')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Email de facturation')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse de facturation')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('billing_country', models.CharField(default='République Démocratique du Congo', max_length=100, verbose_name='Pays')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('due_date', models.DateTimeField(verbose_name="Date d'échéance")),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/', verbose_name='Fichier PDF')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant à rembourser')),
                ('reason', models.TextField(verbose_name='Raison du remboursement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='Paiement')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-requested_at'],
            },
        ),
    ]
