# Generated by Django 5.2.8 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Type'),
        ),
    ]
