# Generated by Django 4.2.7 on 2025-11-09 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Jessna TechLearn', max_length=150, verbose_name='Dénomination sociale'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='data_controller',
            field=models.CharField(default='Chadrack Mbu Jess', max_length=100, verbose_name='Contrôleur des données'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='data_protection_email',
            field=models.EmailField(default='jessnatechlearn@gmail.com', max_length=254, verbose_name='Email protection des données'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='governing_law',
            field=models.CharField(default='République Démocratique du Congo', max_length=100, verbose_name='Droit applicable'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='host_address',
            field=models.CharField(default='525 Brannan Street, Suite 300, San Francisco, CA 94107, USA', max_length=255, verbose_name="Adresse de l'hébergeur"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='host_name',
            field=models.CharField(default='PythonAnywhere', max_length=100, verbose_name="Nom de l'hébergeur"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='host_website',
            field=models.URLField(default='https://pythonanywhere.com', verbose_name="Site web de l'hébergeur"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_representative',
            field=models.CharField(default='Chadrack Mbu Jess', max_length=100, verbose_name='Représentant légal'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_title',
            field=models.CharField(default='Fondateur & Directeur Général', max_length=100, verbose_name='Fonction du représentant'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de la politique de confidentialité'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_version',
            field=models.CharField(default='1.0.2', max_length=20, verbose_name='Version de la politique de confidentialité'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_number',
            field=models.CharField(blank=True, default='En cours', max_length=100, verbose_name="Numéro d'enregistrement"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_number',
            field=models.CharField(blank=True, default='En cours', max_length=100, verbose_name='Numéro fiscal'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date des CGU'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_version',
            field=models.CharField(default='1.0.2', max_length=20, verbose_name='Version des CGU'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='Matadi, Kongo Central, RDC', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='jessnatechlearn@gmail.com', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+243 891 433 419', max_length=20, verbose_name='Téléphone de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Mode maintenance'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='Description du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Jessna TechLearn', max_length=100, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_slogan',
            field=models.CharField(default='Apprendre ici, réussir partout.', max_length=200, verbose_name='Slogan du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='URL Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='URL YouTube'),
        ),
    ]
