# Generated by Django 4.2.7 on 2025-11-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=models.TextField(blank=True, help_text='Le texte complet de la Politique de Confidentialité.', verbose_name='Contenu de la Politique de Confidentialité'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_content',
            field=models.TextField(blank=True, help_text="Le texte complet des Conditions Générales d'Utilisation.", verbose_name='Contenu des CGU'),
        ),
    ]
