# Generated by Django 4.2.7 on 2025-11-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_privacy_policy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='legal_notice_content',
            field=models.TextField(blank=True, help_text='Le texte complet des Mentions Légales.', verbose_name='Contenu des Mentions Légales'),
        ),
    ]
