# Generated by Django 4.2.7 on 2025-11-09 21:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_legal_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='legal_notice_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Le texte complet des Mentions Légales.', verbose_name='Contenu des Mentions Légales'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Le texte complet de la Politique de Confidentialité.', verbose_name='Contenu de la Politique de Confidentialité'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_of_service_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Le texte complet des Conditions Générales d'Utilisation.", verbose_name='Contenu des CGU'),
        ),
    ]
