# Generated by Django 4.2.7 on 2025-11-10 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesettings_legal_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_content',
            field=ckeditor.fields.RichTextField(blank=True, default='\n<h2>1. Responsable du traitement</h2>\n<p>Le responsable du traitement des données personnelles est :</p>\n<div class="info-box">\n    <p><strong>{{ settings.company_name }}</strong></p>\n    <p>{{ settings.address }}</p>\n    <p>Email : <a href="mailto:{{ settings.contact_email }}">{{ settings.contact_email }}</a></p>\n    <p>Téléphone : {{ settings.contact_phone }}</p>\n</div>\n<h2>2. Données collectées</h2>\n<p>Nous collectons les données suivantes :</p>\n<ul>\n    <li><strong>Données d\'identification :</strong> nom, prénom, adresse email</li>\n    <li><strong>Données de connexion :</strong> mot de passe chiffré, date de dernière connexion</li>\n</ul>\n', help_text='Le texte complet de la Politique de Confidentialité.', verbose_name='Contenu de la Politique de Confidentialité'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_of_service_content',
            field=ckeditor.fields.RichTextField(blank=True, default='\n<h2>1. Objet</h2>\n<p>Les présentes conditions générales d\'utilisation (CGU) régissent l\'utilisation de la plateforme d\'apprentissage en ligne {{ settings.company_name }}, accessible à l\'adresse <a href="{{ settings.company_website }}">{{ settings.company_website }}</a>.</p>\n<h2>2. Éditeur</h2>\n<div class="info-box">\n    <p><strong>{{ settings.company_name }}</strong></p>\n    <p>{{ settings.address }}</p>\n    <p>Email : <a href="mailto:{{ settings.contact_email }}">{{ settings.contact_email }}</a></p>\n    <p>Téléphone : {{ settings.contact_phone }}</p>\n</div>\n<h2>3. Acceptation des conditions</h2>\n<p>L\'utilisation de la plateforme {{ settings.company_name }} implique l\'acceptation pleine et entière des présentes conditions d\'utilisation. Si vous n\'acceptez pas ces conditions, vous ne devez pas utiliser nos services.</p>\n', help_text="Le texte complet des Conditions Générales d'Utilisation.", verbose_name='Contenu des CGU'),
        ),
    ]
