# Generated by Django 4.2.7 on 2025-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_privacy_policy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founder_photo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Photo du fondateur'),
        ),
    ]
