# Generated by Django 4.2.7 on 2025-11-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_founder_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'image, utilisé pour le référencement (attribut alt).", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text="Description facultative de l'image.", verbose_name='Description')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image de la galerie',
                'verbose_name_plural': 'Images de la galerie',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
