# Generated by Django 5.2.8 on 2025-12-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_livesession_live_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='live_notification_sent',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_notification_sent',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='starting_notification_sent',
        ),
    ]
