# Generated by Django 5.2.8 on 2025-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0003_remove_livesession_live_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='live_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification de direct envoyée'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification de programmation envoyée'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='starting_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification de début imminent envoyée'),
        ),
    ]
