# Generated by Django 5.1.5 on 2025-08-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('couleur', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Forum',
                'verbose_name_plural': 'Catégories de Forum',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_epingle', models.BooleanField(default=False, verbose_name='Épinglé')),
                ('est_ferme', models.BooleanField(default=False, verbose_name='Fermé')),
                ('est_resolu', models.BooleanField(default=False, verbose_name='Résolu')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('derniere_activite', models.DateTimeField(auto_now_add=True, verbose_name='Dernière activité')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forum.forumcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sujet de Forum',
                'verbose_name_plural': 'Sujets de Forum',
                'ordering': ['-est_epingle', '-derniere_activite'],
                'unique_together': {('categorie', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_solution', models.BooleanField(default=False, verbose_name='Solution')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('likes', models.ManyToManyField(blank=True, related_name='posts_likes', to=settings.AUTH_USER_MODEL, verbose_name="J'aime")),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.forumtopic', verbose_name='Sujet')),
            ],
            options={
                'verbose_name': 'Réponse de Forum',
                'verbose_name_plural': 'Réponses de Forum',
                'ordering': ['cree_le'],
            },
        ),
    ]
