# Generated by Django 5.1.5 on 2025-08-03 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur de fond')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#64748B', max_length=7, verbose_name='Couleur secondaire')),
                ('title_text', models.CharField(default='CERTIFICAT DE RÉUSSITE', max_length=200, verbose_name='Titre')),
                ('subtitle_text', models.CharField(default='TechLearnJess', max_length=200, verbose_name='Sous-titre')),
                ('completion_text', models.CharField(default='a terminé avec succès le cours', max_length=200, verbose_name='Texte de réussite')),
                ('is_default', models.BooleanField(default=False, verbose_name='Modèle par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de certificat',
                'verbose_name_plural': 'Modèles de certificats',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID Certificat')),
                ('student_name', models.CharField(max_length=200, verbose_name="Nom de l'étudiant")),
                ('course_title', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('instructor_name', models.CharField(max_length=200, verbose_name='Nom du formateur')),
                ('completion_date', models.DateField(verbose_name='Date de fin')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/pdf/', verbose_name='Fichier PDF')),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qr/', verbose_name='QR Code')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valide')),
                ('verification_url', models.URLField(blank=True, verbose_name='URL de vérification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issue_date'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
