# Generated by Django 5.2.8 on 2025-12-14 22:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='CD', max_length=2, verbose_name='Pays'),
        ),
    ]
