# Generated by Django 5.2.8 on 2025-12-14 22:50

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Kinshasa', verbose_name='Fuseau horaire'),
        ),
    ]
