# Generated by Django 4.2.7 on 2025-11-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_explanation_question_text_answer_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Méta-description (SEO)'),
        ),
    ]
