# Generated by Django 5.2.8 on 2025-12-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
    ]
