# Generated by Django 5.2.8 on 2025-12-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
    ]
