# Generated by Django 5.2.8 on 2025-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
