# Generated by Django 5.1.5 on 2025-08-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('course_new', 'Nouveau cours'), ('course_update', 'Mise à jour de cours'), ('lesson_new', 'Nouvelle leçon'), ('message', 'Nouveau message'), ('forum_reply', 'Réponse au forum'), ('live_session', 'Session live'), ('certificate', 'Certificat disponible'), ('payment', 'Paiement'), ('system', 'Système')], max_length=20, verbose_name='Type')),
                ('action_url', models.URLField(blank=True, verbose_name="URL d'action")),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Texte du bouton')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_course_new', models.BooleanField(default=True, verbose_name='Nouveaux cours')),
                ('email_course_update', models.BooleanField(default=True, verbose_name='Mises à jour de cours')),
                ('email_message', models.BooleanField(default=True, verbose_name='Messages')),
                ('email_forum_reply', models.BooleanField(default=True, verbose_name='Réponses au forum')),
                ('email_live_session', models.BooleanField(default=True, verbose_name='Sessions live')),
                ('email_certificate', models.BooleanField(default=True, verbose_name='Certificats')),
                ('email_payment', models.BooleanField(default=True, verbose_name='Paiements')),
                ('push_course_new', models.BooleanField(default=True, verbose_name='Nouveaux cours')),
                ('push_course_update', models.BooleanField(default=True, verbose_name='Mises à jour de cours')),
                ('push_message', models.BooleanField(default=True, verbose_name='Messages')),
                ('push_forum_reply', models.BooleanField(default=True, verbose_name='Réponses au forum')),
                ('push_live_session', models.BooleanField(default=True, verbose_name='Sessions live')),
                ('push_certificate', models.BooleanField(default=True, verbose_name='Certificats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notifications',
            },
        ),
    ]
