# Generated by Django 5.2.8 on 2025-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course_new', 'Nouveau cours'), ('course_update', 'Mise à jour de cours'), ('lesson_new', 'Nouvelle leçon'), ('message', 'Nouveau message'), ('forum_reply', 'Réponse au forum'), ('live_session', 'Session live'), ('certificate', 'Certificat disponible'), ('payment', 'Paiement'), ('system', 'Système')], max_length=20, verbose_name='Type'),
        ),
    ]
